#!/bin/bash

cd ~/bin || exit 1
t=$(date +%s)


s=$(stat -t lock/LOCK | cut -d' ' -f9)
case "$s" in
1) ;;
*) echo quitting because of lock ; exit 1;;
esac

ln lock/LOCK lock/$$


s=$(stat -t lock/LOCK | cut -d' ' -f9)
case "$s" in
2) ;;
*) echo quitting because of lock ;  rm -f lock/$$; exit 1;;
esac

./harvest.py > ../logs/H_${t}_1 2> ../logs/H_${t}_2 
./display.py > ../logs/D_${t}_1 2> ../logs/D_${t}_2


lb=$(echo "select last_backup from admin;" | sqlite3 /var/torn/torn_db)
lb=$(expr $lb + 172800)
if [ 1"$lb" -lt 1"$t" ]
then
    echo ".backup /var/torn/auto_backup.$t" | sqlite3 /var/torn/torn_db
    echo "update admin set last_backup=$t;" | sqlite3 /var/torn/torn_db
    echo .fullschema | sqlite3 /var/torn/torn_db > /var/torn/auto_schema.$t
    find /var/torn/ -type f -name 'auto_*' -mtime +14 -delete
fi

rm -f lock/$$
