#!/bin/bash

cd ~/bin || exit 1
t=$(date +%s)


s=$(stat -t lock/LOCK | cut -d' ' -f9)
case "$s" in
1) ;;
*) echo quitting because of lock ; exit 1;;
esac

ln lock/LOCK lock/$$


s=$(stat -t lock/LOCK | cut -d' ' -f9)
case "$s" in
2) ;;
*) echo quitting because of lock ;  rm -f lock/$$; exit 1;;
esac

./harvest.py > ../logs/H_${t}_1 2> ../logs/H_${t}_2 
./display.py > ../logs/D_${t}_1 2> ../logs/D_${t}_2

rm -f lock/$$
